#ifdef TOUCH_CONTROLS
#include "controller_touchscreen_textures.h"

#include "controller_touchscreen_tex_def.c"

const Texture *const touch_textures[TOUCH_TEXTURE_COUNT] = {
    texture_touch_joystick,
    texture_touch_joystick_base,
    texture_touch_c_up,
    texture_touch_c_up_pressed,
    texture_touch_c_down,
    texture_touch_c_down_pressed,
    texture_touch_c_left,
    texture_touch_c_left_pressed,
    texture_touch_c_right,
    texture_touch_c_right_pressed,
    texture_touch_dpad_up,
    texture_touch_dpad_up_pressed,
    texture_touch_dpad_down,
    texture_touch_dpad_down_pressed,
    texture_touch_dpad_left,
    texture_touch_dpad_left_pressed,
    texture_touch_dpad_right,
    texture_touch_dpad_right_pressed,
    texture_touch_a,
    texture_touch_a_pressed,
    texture_touch_b,
    texture_touch_b_pressed,
    texture_touch_x,
    texture_touch_x_pressed,
    texture_touch_y,
    texture_touch_y_pressed,
    texture_touch_start,
    texture_touch_start_pressed,
    texture_touch_l,
    texture_touch_l_pressed,
    texture_touch_r,
    texture_touch_r_pressed,
    texture_touch_z,
    texture_touch_z_pressed,
    texture_touch_chat,
    texture_touch_chat_pressed,
    texture_touch_playerlist,
    texture_touch_playerlist_pressed,
    texture_touch_console,
    texture_touch_console_pressed,
    texture_touch_check,
    texture_touch_cross,
    texture_touch_reset,
    texture_touch_snap,
    texture_touch_trash,
}; 
#endif