name: Build coop

on:
  workflow_dispatch:

env:
  COOP_SERVER_IP: ${{ secrets.COOP_SERVER_IP }}

jobs:
    build-android:
        if: ${{ (github.event_name != 'push' || contains(github.event.head_commit.message, '[build]')) && github.event.pull_request.draft == false }}
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'

            - name: Install dependencies
              run: |
                sudo apt update
                sudo apt install -y build-essential git python3 libglew-dev libsdl2-dev libz-dev libcurl4-openssl-dev g++ zip unzip wget apksigner
                mkdir -p $HOME/android-sdk/cmdline-tools
                cd $HOME/android-sdk/cmdline-tools
                wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
                unzip tools.zip
                rm tools.zip
                mv cmdline-tools latest
                export ANDROID_HOME=$HOME/android-sdk
                export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
                yes | sdkmanager --licenses
                sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"
                echo "sdk.dir=$HOME/android-sdk" > $GITHUB_WORKSPACE/platform/local.properties

            - name: Build the game
              run: |
                make -j$(nproc) TOUCH_CONTROLS=1 SERVER_IP="$COOP_SERVER_IP"
                chmod +x ./platform/gradlew
                ./platform/gradlew assembleRelease
                apksigner sign \
                  --key platform/android/key.pk8 \
                  --cert platform/android/certificate.pem \
                  platform/app/build/outputs/apk/release/app-release-unsigned.apk
                mv platform/app/build/outputs/apk/release/app-release-unsigned.apk build/us_pc/sm64coopdx.apk

            - name: Generate hash
              run: |
                cd tools
                g++ -std=c++17 -o hash_file hash_file.cpp
                for f in ../platform/app/build/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib/*/libmain.so; do
                    abi=$(basename $(dirname "$f"))
                    hash=$(./hash_file "$f")
                    echo "::notice title=libmain.so ($abi)::$hash"
                done

            - name: Zip the .apk package
              run: |
                cd ./build/us_pc
                zip -r sm64coopdx_Android.zip sm64coopdx.apk
            
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: sm64coopdx-android
                path: ./build/us_pc/sm64coopdx_Android.zip